#! /bin/sh
cp ~/Library/Lutsko/Lutsko96.pdf ./
cp ~/Library/Lutsko/LutskoJCP.pdf ./
cp ~/Library/Lutsko/LutskoEnskog.pdf ./
cp ~/Library/Lutsko/Lutsko_EnskogPRL.pdf ./
cp ~/Library/Lutsko/Lutsko2001.pdf ./
cp ~/Library/Lutsko/LutskoHCS.pdf ./
cp ~/Library/Lutsko/LutskoPolydisperse.pdf ./
cp ~/Library/Lutsko/Lutsko_Fluctuations.pdf ./
cp ~/Library/Lutsko/Lutsko_Shear_Fluctuations.pdf ./
cp ~/Library/Lutsko/Gaspard.pdf ./
cp ~/Library/Lutsko/Lutsko_PRE_2005_2.pdf ./
cp ~/Library/Lutsko/LutskoNicolis.pdf ./
cp ~/Library/Lutsko/Lutsko_1985_1.pdf ./
cp ~/Library/Lutsko/Lutsko_1986_1.pdf ./
cp ~/Library/Lutsko/Lutsko_1988_1.pdf ./
cp ~/Library/Lutsko/Lutsko_1988_2.pdf ./
cp ~/Library/Lutsko/Lutsko_1989_1.pdf ./
cp ~/Library/Lutsko/Lutsko_1989_2.pdf ./
cp ~/Library/Lutsko/Lutsko_1990_1.pdf ./
cp ~/Library/Lutsko/Lutsko_1990_2.pdf ./
cp ~/Library/Lutsko/Lutsko_1991_1.pdf ./
cp ~/Library/Lutsko/Lutsko_1992_1.pdf ./
cp ~/Library/Lutsko/Lutsko_1996_1.pdf ./
cp ~/Library/Lutsko/Lutsko_1998_1.pdf ./
cp ~/Library/Lutsko/Lutsko_PRE_2002_1.pdf ./
cp ~/Library/Lutsko/Lutsko_PRE_2002_2.pdf ./
cp ~/Library/Lutsko/Lutsko_PRE_2002_3.pdf ./
cp ~/Library/Lutsko/Lutsko_PRB_2005_1.pdf ./
cp ~/Library/Lutsko/Lutsko_JSP_2003.pdf ./
cp ~/Library/Lutsko/Lutsko_EPL_2005.pdf ./
cp ~/Library/Lutsko/Lutsko_PRE_2006_1.pdf ./
cp ~/Library/Lutsko/Lutsko_PRL_2006_1.pdf ./
cp ~/Library/Lutsko/Lutsko_Physica_2006_1.pdf ./
cp ~/Library/Lutsko/Lutsko_Physica_2006_2.pdf ./
cp ~/Library/Lutsko/Lutsko_JCP_2006.pdf ./
cp ~/Library/Lutsko/Lutsko_PRE_2006_2.pdf ./
cp ~/Library/Lutsko/Lutsko_PRE_2006_3.pdf ./
cp ~/Library/Lutsko/Lutsko_JCP_2007.pdf ./
cp ~/Library/Lutsko/Boon_Lutsko_AIP_2007.pdf ./
cp ~/Library/Lutsko/Boon_Lutsko_EPL_2007.pdf ./
cp ~/Library/Lutsko/Boon_Lutsko_AIP_2007.pdf ./
cp ~/Library/Lutsko/Lutsko_PRE_2008_1.pdf ./
cp ~/Library/Lutsko/Lutsko_JCP_2008_1.pdf ./

